language: java
sudo: required
jdk:
- openjdk8

install: 
- mvn  -N io.takari:maven:wrapper

script:
- ./mvnw clean install 
deploy:
- provider: heroku
  api_key: $HEROKU_API_KEY
  app: java-microservice
  skip_cleanup: true
  on:
    branch:
